### YamlMime:ManagedReference
items:
- uid: SombraStudios.Shared.Gameplay.Spawners.Wave.WaveConfig
  commentId: T:SombraStudios.Shared.Gameplay.Spawners.Wave.WaveConfig
  id: WaveConfig
  parent: SombraStudios.Shared.Gameplay.Spawners.Wave
  children:
  - SombraStudios.Shared.Gameplay.Spawners.Wave.WaveConfig.GetMoveSpeed
  - SombraStudios.Shared.Gameplay.Spawners.Wave.WaveConfig.GetPrefab
  - SombraStudios.Shared.Gameplay.Spawners.Wave.WaveConfig.GetQuantity
  - SombraStudios.Shared.Gameplay.Spawners.Wave.WaveConfig.GetSpawnRandomFactor
  - SombraStudios.Shared.Gameplay.Spawners.Wave.WaveConfig.GetTimeBetweenSpawns
  langs:
  - csharp
  - vb
  name: WaveConfig
  nameWithType: WaveConfig
  fullName: SombraStudios.Shared.Gameplay.Spawners.Wave.WaveConfig
  type: Class
  source:
    remote:
      path: Gameplay/Spawners/Wave/WaveConfig.cs
      branch: main
      repo: https://github.com/manuelfalonso/Unity-Scripts.git
    id: WaveConfig
    path: ../Gameplay/Spawners/Wave/WaveConfig.cs
    startLine: 4
  assemblies:
  - SombraStudios.Shared.Gameplay
  namespace: SombraStudios.Shared.Gameplay.Spawners.Wave
  syntax:
    content: >-
      [CreateAssetMenu(menuName = "Wave Config")]

      public class WaveConfig : ScriptableObject
    content.vb: >-
      <CreateAssetMenu(menuName:="Wave Config")>

      Public Class WaveConfig Inherits ScriptableObject
  inheritance:
  - System.Object
  - UnityEngine.Object
  - UnityEngine.ScriptableObject
  attributes:
  - type: UnityEngine.CreateAssetMenuAttribute
    ctor: UnityEngine.CreateAssetMenuAttribute.#ctor
    arguments: []
    namedArguments:
    - name: menuName
      type: System.String
      value: Wave Config
- uid: SombraStudios.Shared.Gameplay.Spawners.Wave.WaveConfig.GetPrefab
  commentId: M:SombraStudios.Shared.Gameplay.Spawners.Wave.WaveConfig.GetPrefab
  id: GetPrefab
  parent: SombraStudios.Shared.Gameplay.Spawners.Wave.WaveConfig
  langs:
  - csharp
  - vb
  name: GetPrefab()
  nameWithType: WaveConfig.GetPrefab()
  fullName: SombraStudios.Shared.Gameplay.Spawners.Wave.WaveConfig.GetPrefab()
  type: Method
  source:
    remote:
      path: Gameplay/Spawners/Wave/WaveConfig.cs
      branch: main
      repo: https://github.com/manuelfalonso/Unity-Scripts.git
    id: GetPrefab
    path: ../Gameplay/Spawners/Wave/WaveConfig.cs
    startLine: 14
  assemblies:
  - SombraStudios.Shared.Gameplay
  namespace: SombraStudios.Shared.Gameplay.Spawners.Wave
  syntax:
    content: public GameObject GetPrefab()
    return:
      type: UnityEngine.GameObject
    content.vb: Public Function GetPrefab() As GameObject
  overload: SombraStudios.Shared.Gameplay.Spawners.Wave.WaveConfig.GetPrefab*
- uid: SombraStudios.Shared.Gameplay.Spawners.Wave.WaveConfig.GetTimeBetweenSpawns
  commentId: M:SombraStudios.Shared.Gameplay.Spawners.Wave.WaveConfig.GetTimeBetweenSpawns
  id: GetTimeBetweenSpawns
  parent: SombraStudios.Shared.Gameplay.Spawners.Wave.WaveConfig
  langs:
  - csharp
  - vb
  name: GetTimeBetweenSpawns()
  nameWithType: WaveConfig.GetTimeBetweenSpawns()
  fullName: SombraStudios.Shared.Gameplay.Spawners.Wave.WaveConfig.GetTimeBetweenSpawns()
  type: Method
  source:
    remote:
      path: Gameplay/Spawners/Wave/WaveConfig.cs
      branch: main
      repo: https://github.com/manuelfalonso/Unity-Scripts.git
    id: GetTimeBetweenSpawns
    path: ../Gameplay/Spawners/Wave/WaveConfig.cs
    startLine: 16
  assemblies:
  - SombraStudios.Shared.Gameplay
  namespace: SombraStudios.Shared.Gameplay.Spawners.Wave
  syntax:
    content: public float GetTimeBetweenSpawns()
    return:
      type: System.Single
    content.vb: Public Function GetTimeBetweenSpawns() As Single
  overload: SombraStudios.Shared.Gameplay.Spawners.Wave.WaveConfig.GetTimeBetweenSpawns*
- uid: SombraStudios.Shared.Gameplay.Spawners.Wave.WaveConfig.GetSpawnRandomFactor
  commentId: M:SombraStudios.Shared.Gameplay.Spawners.Wave.WaveConfig.GetSpawnRandomFactor
  id: GetSpawnRandomFactor
  parent: SombraStudios.Shared.Gameplay.Spawners.Wave.WaveConfig
  langs:
  - csharp
  - vb
  name: GetSpawnRandomFactor()
  nameWithType: WaveConfig.GetSpawnRandomFactor()
  fullName: SombraStudios.Shared.Gameplay.Spawners.Wave.WaveConfig.GetSpawnRandomFactor()
  type: Method
  source:
    remote:
      path: Gameplay/Spawners/Wave/WaveConfig.cs
      branch: main
      repo: https://github.com/manuelfalonso/Unity-Scripts.git
    id: GetSpawnRandomFactor
    path: ../Gameplay/Spawners/Wave/WaveConfig.cs
    startLine: 18
  assemblies:
  - SombraStudios.Shared.Gameplay
  namespace: SombraStudios.Shared.Gameplay.Spawners.Wave
  syntax:
    content: public float GetSpawnRandomFactor()
    return:
      type: System.Single
    content.vb: Public Function GetSpawnRandomFactor() As Single
  overload: SombraStudios.Shared.Gameplay.Spawners.Wave.WaveConfig.GetSpawnRandomFactor*
- uid: SombraStudios.Shared.Gameplay.Spawners.Wave.WaveConfig.GetQuantity
  commentId: M:SombraStudios.Shared.Gameplay.Spawners.Wave.WaveConfig.GetQuantity
  id: GetQuantity
  parent: SombraStudios.Shared.Gameplay.Spawners.Wave.WaveConfig
  langs:
  - csharp
  - vb
  name: GetQuantity()
  nameWithType: WaveConfig.GetQuantity()
  fullName: SombraStudios.Shared.Gameplay.Spawners.Wave.WaveConfig.GetQuantity()
  type: Method
  source:
    remote:
      path: Gameplay/Spawners/Wave/WaveConfig.cs
      branch: main
      repo: https://github.com/manuelfalonso/Unity-Scripts.git
    id: GetQuantity
    path: ../Gameplay/Spawners/Wave/WaveConfig.cs
    startLine: 20
  assemblies:
  - SombraStudios.Shared.Gameplay
  namespace: SombraStudios.Shared.Gameplay.Spawners.Wave
  syntax:
    content: public int GetQuantity()
    return:
      type: System.Int32
    content.vb: Public Function GetQuantity() As Integer
  overload: SombraStudios.Shared.Gameplay.Spawners.Wave.WaveConfig.GetQuantity*
- uid: SombraStudios.Shared.Gameplay.Spawners.Wave.WaveConfig.GetMoveSpeed
  commentId: M:SombraStudios.Shared.Gameplay.Spawners.Wave.WaveConfig.GetMoveSpeed
  id: GetMoveSpeed
  parent: SombraStudios.Shared.Gameplay.Spawners.Wave.WaveConfig
  langs:
  - csharp
  - vb
  name: GetMoveSpeed()
  nameWithType: WaveConfig.GetMoveSpeed()
  fullName: SombraStudios.Shared.Gameplay.Spawners.Wave.WaveConfig.GetMoveSpeed()
  type: Method
  source:
    remote:
      path: Gameplay/Spawners/Wave/WaveConfig.cs
      branch: main
      repo: https://github.com/manuelfalonso/Unity-Scripts.git
    id: GetMoveSpeed
    path: ../Gameplay/Spawners/Wave/WaveConfig.cs
    startLine: 22
  assemblies:
  - SombraStudios.Shared.Gameplay
  namespace: SombraStudios.Shared.Gameplay.Spawners.Wave
  syntax:
    content: public float GetMoveSpeed()
    return:
      type: System.Single
    content.vb: Public Function GetMoveSpeed() As Single
  overload: SombraStudios.Shared.Gameplay.Spawners.Wave.WaveConfig.GetMoveSpeed*
references:
- uid: SombraStudios.Shared.Gameplay.Spawners.Wave
  commentId: N:SombraStudios.Shared.Gameplay.Spawners.Wave
  href: SombraStudios.html
  name: SombraStudios.Shared.Gameplay.Spawners.Wave
  nameWithType: SombraStudios.Shared.Gameplay.Spawners.Wave
  fullName: SombraStudios.Shared.Gameplay.Spawners.Wave
  spec.csharp:
  - uid: SombraStudios
    name: SombraStudios
    href: SombraStudios.html
  - name: .
  - uid: SombraStudios.Shared
    name: Shared
    href: SombraStudios.Shared.html
  - name: .
  - uid: SombraStudios.Shared.Gameplay
    name: Gameplay
    href: SombraStudios.Shared.Gameplay.html
  - name: .
  - uid: SombraStudios.Shared.Gameplay.Spawners
    name: Spawners
    href: SombraStudios.Shared.Gameplay.Spawners.html
  - name: .
  - uid: SombraStudios.Shared.Gameplay.Spawners.Wave
    name: Wave
    href: SombraStudios.Shared.Gameplay.Spawners.Wave.html
  spec.vb:
  - uid: SombraStudios
    name: SombraStudios
    href: SombraStudios.html
  - name: .
  - uid: SombraStudios.Shared
    name: Shared
    href: SombraStudios.Shared.html
  - name: .
  - uid: SombraStudios.Shared.Gameplay
    name: Gameplay
    href: SombraStudios.Shared.Gameplay.html
  - name: .
  - uid: SombraStudios.Shared.Gameplay.Spawners
    name: Spawners
    href: SombraStudios.Shared.Gameplay.Spawners.html
  - name: .
  - uid: SombraStudios.Shared.Gameplay.Spawners.Wave
    name: Wave
    href: SombraStudios.Shared.Gameplay.Spawners.Wave.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: UnityEngine.Object
  commentId: T:UnityEngine.Object
  parent: UnityEngine
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: UnityEngine.Object
- uid: UnityEngine.ScriptableObject
  commentId: T:UnityEngine.ScriptableObject
  parent: UnityEngine
  isExternal: true
  name: ScriptableObject
  nameWithType: ScriptableObject
  fullName: UnityEngine.ScriptableObject
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: UnityEngine
  commentId: N:UnityEngine
  isExternal: true
  name: UnityEngine
  nameWithType: UnityEngine
  fullName: UnityEngine
- uid: SombraStudios.Shared.Gameplay.Spawners.Wave.WaveConfig.GetPrefab*
  commentId: Overload:SombraStudios.Shared.Gameplay.Spawners.Wave.WaveConfig.GetPrefab
  href: SombraStudios.Shared.Gameplay.Spawners.Wave.WaveConfig.html#SombraStudios_Shared_Gameplay_Spawners_Wave_WaveConfig_GetPrefab
  name: GetPrefab
  nameWithType: WaveConfig.GetPrefab
  fullName: SombraStudios.Shared.Gameplay.Spawners.Wave.WaveConfig.GetPrefab
- uid: UnityEngine.GameObject
  commentId: T:UnityEngine.GameObject
  parent: UnityEngine
  isExternal: true
  name: GameObject
  nameWithType: GameObject
  fullName: UnityEngine.GameObject
- uid: SombraStudios.Shared.Gameplay.Spawners.Wave.WaveConfig.GetTimeBetweenSpawns*
  commentId: Overload:SombraStudios.Shared.Gameplay.Spawners.Wave.WaveConfig.GetTimeBetweenSpawns
  href: SombraStudios.Shared.Gameplay.Spawners.Wave.WaveConfig.html#SombraStudios_Shared_Gameplay_Spawners_Wave_WaveConfig_GetTimeBetweenSpawns
  name: GetTimeBetweenSpawns
  nameWithType: WaveConfig.GetTimeBetweenSpawns
  fullName: SombraStudios.Shared.Gameplay.Spawners.Wave.WaveConfig.GetTimeBetweenSpawns
- uid: System.Single
  commentId: T:System.Single
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.single
  name: float
  nameWithType: float
  fullName: float
  nameWithType.vb: Single
  fullName.vb: Single
  name.vb: Single
- uid: SombraStudios.Shared.Gameplay.Spawners.Wave.WaveConfig.GetSpawnRandomFactor*
  commentId: Overload:SombraStudios.Shared.Gameplay.Spawners.Wave.WaveConfig.GetSpawnRandomFactor
  href: SombraStudios.Shared.Gameplay.Spawners.Wave.WaveConfig.html#SombraStudios_Shared_Gameplay_Spawners_Wave_WaveConfig_GetSpawnRandomFactor
  name: GetSpawnRandomFactor
  nameWithType: WaveConfig.GetSpawnRandomFactor
  fullName: SombraStudios.Shared.Gameplay.Spawners.Wave.WaveConfig.GetSpawnRandomFactor
- uid: SombraStudios.Shared.Gameplay.Spawners.Wave.WaveConfig.GetQuantity*
  commentId: Overload:SombraStudios.Shared.Gameplay.Spawners.Wave.WaveConfig.GetQuantity
  href: SombraStudios.Shared.Gameplay.Spawners.Wave.WaveConfig.html#SombraStudios_Shared_Gameplay_Spawners_Wave_WaveConfig_GetQuantity
  name: GetQuantity
  nameWithType: WaveConfig.GetQuantity
  fullName: SombraStudios.Shared.Gameplay.Spawners.Wave.WaveConfig.GetQuantity
- uid: System.Int32
  commentId: T:System.Int32
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.int32
  name: int
  nameWithType: int
  fullName: int
  nameWithType.vb: Integer
  fullName.vb: Integer
  name.vb: Integer
- uid: SombraStudios.Shared.Gameplay.Spawners.Wave.WaveConfig.GetMoveSpeed*
  commentId: Overload:SombraStudios.Shared.Gameplay.Spawners.Wave.WaveConfig.GetMoveSpeed
  href: SombraStudios.Shared.Gameplay.Spawners.Wave.WaveConfig.html#SombraStudios_Shared_Gameplay_Spawners_Wave_WaveConfig_GetMoveSpeed
  name: GetMoveSpeed
  nameWithType: WaveConfig.GetMoveSpeed
  fullName: SombraStudios.Shared.Gameplay.Spawners.Wave.WaveConfig.GetMoveSpeed
