### YamlMime:ManagedReference
items:
- uid: SombraStudios.Shared.Audio.AudioVolumeConfigurator
  commentId: T:SombraStudios.Shared.Audio.AudioVolumeConfigurator
  id: AudioVolumeConfigurator
  parent: SombraStudios.Shared.Audio
  children:
  - SombraStudios.Shared.Audio.AudioVolumeConfigurator.Instance
  - SombraStudios.Shared.Audio.AudioVolumeConfigurator.SetMainVolume(System.Single)
  - SombraStudios.Shared.Audio.AudioVolumeConfigurator.SetMusicVolume(System.Single)
  langs:
  - csharp
  - vb
  name: AudioVolumeConfigurator
  nameWithType: AudioVolumeConfigurator
  fullName: SombraStudios.Shared.Audio.AudioVolumeConfigurator
  type: Class
  source:
    remote:
      path: Audio/AudioVolumeConfigurator.cs
      branch: main
      repo: https://github.com/manuelfalonso/Unity-Scripts.git
    id: AudioVolumeConfigurator
    path: ../Assets/Sombra Studios/Shared/Audio/AudioVolumeConfigurator.cs
    startLine: 17
  assemblies:
  - SombraStudios.Shared.Audio
  namespace: SombraStudios.Shared.Audio
  summary: >-
    Singleton Class to manage AudioMixer volumes.

    Provides public functions that can be called when these values change.

    It must receive values from 0.0001 to 1. For example by a slider.

    Uses PlayerPrefs to save volume OnDisable and load them OnEnable.

    Requiered: In the Audio Mixer create two groups. One for Main and other

    for Music. Music is child of Main. Expose volumne by right clicking

    Match the name used by the script.

    One slider for each volume.
  example: []
  syntax:
    content: 'public class AudioVolumeConfigurator : MonoBehaviour'
    content.vb: Public Class AudioVolumeConfigurator Inherits MonoBehaviour
  inheritance:
  - System.Object
  - UnityEngine.Object
  - UnityEngine.Component
  - UnityEngine.Behaviour
  - UnityEngine.MonoBehaviour
  extensionMethods:
  - UnityEngine.MonoBehaviour.SombraStudios.Shared.Extensions.MonoBehaviourExtensions.SafeInit``1({T}@)
- uid: SombraStudios.Shared.Audio.AudioVolumeConfigurator.Instance
  commentId: P:SombraStudios.Shared.Audio.AudioVolumeConfigurator.Instance
  id: Instance
  parent: SombraStudios.Shared.Audio.AudioVolumeConfigurator
  langs:
  - csharp
  - vb
  name: Instance
  nameWithType: AudioVolumeConfigurator.Instance
  fullName: SombraStudios.Shared.Audio.AudioVolumeConfigurator.Instance
  type: Property
  source:
    remote:
      path: Audio/AudioVolumeConfigurator.cs
      branch: main
      repo: https://github.com/manuelfalonso/Unity-Scripts.git
    id: Instance
    path: ../Assets/Sombra Studios/Shared/Audio/AudioVolumeConfigurator.cs
    startLine: 31
  assemblies:
  - SombraStudios.Shared.Audio
  namespace: SombraStudios.Shared.Audio
  syntax:
    content: public static AudioVolumeConfigurator Instance { get; }
    parameters: []
    return:
      type: SombraStudios.Shared.Audio.AudioVolumeConfigurator
    content.vb: Public Shared Property Instance As AudioVolumeConfigurator
  overload: SombraStudios.Shared.Audio.AudioVolumeConfigurator.Instance*
- uid: SombraStudios.Shared.Audio.AudioVolumeConfigurator.SetMainVolume(System.Single)
  commentId: M:SombraStudios.Shared.Audio.AudioVolumeConfigurator.SetMainVolume(System.Single)
  id: SetMainVolume(System.Single)
  parent: SombraStudios.Shared.Audio.AudioVolumeConfigurator
  langs:
  - csharp
  - vb
  name: SetMainVolume(float)
  nameWithType: AudioVolumeConfigurator.SetMainVolume(float)
  fullName: SombraStudios.Shared.Audio.AudioVolumeConfigurator.SetMainVolume(float)
  type: Method
  source:
    remote:
      path: Audio/AudioVolumeConfigurator.cs
      branch: main
      repo: https://github.com/manuelfalonso/Unity-Scripts.git
    id: SetMainVolume
    path: ../Assets/Sombra Studios/Shared/Audio/AudioVolumeConfigurator.cs
    startLine: 75
  assemblies:
  - SombraStudios.Shared.Audio
  namespace: SombraStudios.Shared.Audio
  syntax:
    content: public void SetMainVolume(float rawVolume)
    parameters:
    - id: rawVolume
      type: System.Single
    content.vb: Public Sub SetMainVolume(rawVolume As Single)
  overload: SombraStudios.Shared.Audio.AudioVolumeConfigurator.SetMainVolume*
  nameWithType.vb: AudioVolumeConfigurator.SetMainVolume(Single)
  fullName.vb: SombraStudios.Shared.Audio.AudioVolumeConfigurator.SetMainVolume(Single)
  name.vb: SetMainVolume(Single)
- uid: SombraStudios.Shared.Audio.AudioVolumeConfigurator.SetMusicVolume(System.Single)
  commentId: M:SombraStudios.Shared.Audio.AudioVolumeConfigurator.SetMusicVolume(System.Single)
  id: SetMusicVolume(System.Single)
  parent: SombraStudios.Shared.Audio.AudioVolumeConfigurator
  langs:
  - csharp
  - vb
  name: SetMusicVolume(float)
  nameWithType: AudioVolumeConfigurator.SetMusicVolume(float)
  fullName: SombraStudios.Shared.Audio.AudioVolumeConfigurator.SetMusicVolume(float)
  type: Method
  source:
    remote:
      path: Audio/AudioVolumeConfigurator.cs
      branch: main
      repo: https://github.com/manuelfalonso/Unity-Scripts.git
    id: SetMusicVolume
    path: ../Assets/Sombra Studios/Shared/Audio/AudioVolumeConfigurator.cs
    startLine: 81
  assemblies:
  - SombraStudios.Shared.Audio
  namespace: SombraStudios.Shared.Audio
  syntax:
    content: public void SetMusicVolume(float rawVolume)
    parameters:
    - id: rawVolume
      type: System.Single
    content.vb: Public Sub SetMusicVolume(rawVolume As Single)
  overload: SombraStudios.Shared.Audio.AudioVolumeConfigurator.SetMusicVolume*
  nameWithType.vb: AudioVolumeConfigurator.SetMusicVolume(Single)
  fullName.vb: SombraStudios.Shared.Audio.AudioVolumeConfigurator.SetMusicVolume(Single)
  name.vb: SetMusicVolume(Single)
references:
- uid: SombraStudios.Shared.Audio
  commentId: N:SombraStudios.Shared.Audio
  href: SombraStudios.html
  name: SombraStudios.Shared.Audio
  nameWithType: SombraStudios.Shared.Audio
  fullName: SombraStudios.Shared.Audio
  spec.csharp:
  - uid: SombraStudios
    name: SombraStudios
    href: SombraStudios.html
  - name: .
  - uid: SombraStudios.Shared
    name: Shared
    href: SombraStudios.Shared.html
  - name: .
  - uid: SombraStudios.Shared.Audio
    name: Audio
    href: SombraStudios.Shared.Audio.html
  spec.vb:
  - uid: SombraStudios
    name: SombraStudios
    href: SombraStudios.html
  - name: .
  - uid: SombraStudios.Shared
    name: Shared
    href: SombraStudios.Shared.html
  - name: .
  - uid: SombraStudios.Shared.Audio
    name: Audio
    href: SombraStudios.Shared.Audio.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: UnityEngine.Object
  commentId: T:UnityEngine.Object
  parent: UnityEngine
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: UnityEngine.Object
- uid: UnityEngine.Component
  commentId: T:UnityEngine.Component
  parent: UnityEngine
  isExternal: true
  name: Component
  nameWithType: Component
  fullName: UnityEngine.Component
- uid: UnityEngine.Behaviour
  commentId: T:UnityEngine.Behaviour
  parent: UnityEngine
  isExternal: true
  name: Behaviour
  nameWithType: Behaviour
  fullName: UnityEngine.Behaviour
- uid: UnityEngine.MonoBehaviour
  commentId: T:UnityEngine.MonoBehaviour
  parent: UnityEngine
  isExternal: true
  name: MonoBehaviour
  nameWithType: MonoBehaviour
  fullName: UnityEngine.MonoBehaviour
- uid: UnityEngine.MonoBehaviour.SombraStudios.Shared.Extensions.MonoBehaviourExtensions.SafeInit``1({T}@)
  commentId: M:SombraStudios.Shared.Extensions.MonoBehaviourExtensions.SafeInit``1(UnityEngine.MonoBehaviour,``0@)
  parent: SombraStudios.Shared.Extensions.MonoBehaviourExtensions
  definition: SombraStudios.Shared.Extensions.MonoBehaviourExtensions.SafeInit``1(UnityEngine.MonoBehaviour,``0@)
  href: SombraStudios.Shared.Extensions.MonoBehaviourExtensions.html#SombraStudios_Shared_Extensions_MonoBehaviourExtensions_SafeInit__1_UnityEngine_MonoBehaviour___0__
  name: SafeInit<T>(MonoBehaviour, ref T)
  nameWithType: MonoBehaviourExtensions.SafeInit<T>(MonoBehaviour, ref T)
  fullName: SombraStudios.Shared.Extensions.MonoBehaviourExtensions.SafeInit<T>(UnityEngine.MonoBehaviour, ref T)
  nameWithType.vb: MonoBehaviourExtensions.SafeInit(Of T)(MonoBehaviour, T)
  fullName.vb: SombraStudios.Shared.Extensions.MonoBehaviourExtensions.SafeInit(Of T)(UnityEngine.MonoBehaviour, T)
  name.vb: SafeInit(Of T)(MonoBehaviour, T)
  spec.csharp:
  - uid: SombraStudios.Shared.Extensions.MonoBehaviourExtensions.SafeInit``1(UnityEngine.MonoBehaviour,``0@)
    name: SafeInit
    href: SombraStudios.Shared.Extensions.MonoBehaviourExtensions.html#SombraStudios_Shared_Extensions_MonoBehaviourExtensions_SafeInit__1_UnityEngine_MonoBehaviour___0__
  - name: <
  - name: T
  - name: '>'
  - name: (
  - uid: UnityEngine.MonoBehaviour
    name: MonoBehaviour
    isExternal: true
  - name: ','
  - name: " "
  - name: ref
  - name: " "
  - name: T
  - name: )
  spec.vb:
  - uid: SombraStudios.Shared.Extensions.MonoBehaviourExtensions.SafeInit``1(UnityEngine.MonoBehaviour,``0@)
    name: SafeInit
    href: SombraStudios.Shared.Extensions.MonoBehaviourExtensions.html#SombraStudios_Shared_Extensions_MonoBehaviourExtensions_SafeInit__1_UnityEngine_MonoBehaviour___0__
  - name: (
  - name: Of
  - name: " "
  - name: T
  - name: )
  - name: (
  - uid: UnityEngine.MonoBehaviour
    name: MonoBehaviour
    isExternal: true
  - name: ','
  - name: " "
  - name: T
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: UnityEngine
  commentId: N:UnityEngine
  isExternal: true
  name: UnityEngine
  nameWithType: UnityEngine
  fullName: UnityEngine
- uid: SombraStudios.Shared.Extensions.MonoBehaviourExtensions.SafeInit``1(UnityEngine.MonoBehaviour,``0@)
  commentId: M:SombraStudios.Shared.Extensions.MonoBehaviourExtensions.SafeInit``1(UnityEngine.MonoBehaviour,``0@)
  isExternal: true
  href: SombraStudios.Shared.Extensions.MonoBehaviourExtensions.html#SombraStudios_Shared_Extensions_MonoBehaviourExtensions_SafeInit__1_UnityEngine_MonoBehaviour___0__
  name: SafeInit<T>(MonoBehaviour, ref T)
  nameWithType: MonoBehaviourExtensions.SafeInit<T>(MonoBehaviour, ref T)
  fullName: SombraStudios.Shared.Extensions.MonoBehaviourExtensions.SafeInit<T>(UnityEngine.MonoBehaviour, ref T)
  nameWithType.vb: MonoBehaviourExtensions.SafeInit(Of T)(MonoBehaviour, T)
  fullName.vb: SombraStudios.Shared.Extensions.MonoBehaviourExtensions.SafeInit(Of T)(UnityEngine.MonoBehaviour, T)
  name.vb: SafeInit(Of T)(MonoBehaviour, T)
  spec.csharp:
  - uid: SombraStudios.Shared.Extensions.MonoBehaviourExtensions.SafeInit``1(UnityEngine.MonoBehaviour,``0@)
    name: SafeInit
    href: SombraStudios.Shared.Extensions.MonoBehaviourExtensions.html#SombraStudios_Shared_Extensions_MonoBehaviourExtensions_SafeInit__1_UnityEngine_MonoBehaviour___0__
  - name: <
  - name: T
  - name: '>'
  - name: (
  - uid: UnityEngine.MonoBehaviour
    name: MonoBehaviour
    isExternal: true
  - name: ','
  - name: " "
  - name: ref
  - name: " "
  - name: T
  - name: )
  spec.vb:
  - uid: SombraStudios.Shared.Extensions.MonoBehaviourExtensions.SafeInit``1(UnityEngine.MonoBehaviour,``0@)
    name: SafeInit
    href: SombraStudios.Shared.Extensions.MonoBehaviourExtensions.html#SombraStudios_Shared_Extensions_MonoBehaviourExtensions_SafeInit__1_UnityEngine_MonoBehaviour___0__
  - name: (
  - name: Of
  - name: " "
  - name: T
  - name: )
  - name: (
  - uid: UnityEngine.MonoBehaviour
    name: MonoBehaviour
    isExternal: true
  - name: ','
  - name: " "
  - name: T
  - name: )
- uid: SombraStudios.Shared.Extensions.MonoBehaviourExtensions
  commentId: T:SombraStudios.Shared.Extensions.MonoBehaviourExtensions
  parent: SombraStudios.Shared.Extensions
  href: SombraStudios.Shared.Extensions.MonoBehaviourExtensions.html
  name: MonoBehaviourExtensions
  nameWithType: MonoBehaviourExtensions
  fullName: SombraStudios.Shared.Extensions.MonoBehaviourExtensions
- uid: SombraStudios.Shared.Extensions
  commentId: N:SombraStudios.Shared.Extensions
  href: SombraStudios.html
  name: SombraStudios.Shared.Extensions
  nameWithType: SombraStudios.Shared.Extensions
  fullName: SombraStudios.Shared.Extensions
  spec.csharp:
  - uid: SombraStudios
    name: SombraStudios
    href: SombraStudios.html
  - name: .
  - uid: SombraStudios.Shared
    name: Shared
    href: SombraStudios.Shared.html
  - name: .
  - uid: SombraStudios.Shared.Extensions
    name: Extensions
    href: SombraStudios.Shared.Extensions.html
  spec.vb:
  - uid: SombraStudios
    name: SombraStudios
    href: SombraStudios.html
  - name: .
  - uid: SombraStudios.Shared
    name: Shared
    href: SombraStudios.Shared.html
  - name: .
  - uid: SombraStudios.Shared.Extensions
    name: Extensions
    href: SombraStudios.Shared.Extensions.html
- uid: SombraStudios.Shared.Audio.AudioVolumeConfigurator.Instance*
  commentId: Overload:SombraStudios.Shared.Audio.AudioVolumeConfigurator.Instance
  href: SombraStudios.Shared.Audio.AudioVolumeConfigurator.html#SombraStudios_Shared_Audio_AudioVolumeConfigurator_Instance
  name: Instance
  nameWithType: AudioVolumeConfigurator.Instance
  fullName: SombraStudios.Shared.Audio.AudioVolumeConfigurator.Instance
- uid: SombraStudios.Shared.Audio.AudioVolumeConfigurator
  commentId: T:SombraStudios.Shared.Audio.AudioVolumeConfigurator
  parent: SombraStudios.Shared.Audio
  href: SombraStudios.Shared.Audio.AudioVolumeConfigurator.html
  name: AudioVolumeConfigurator
  nameWithType: AudioVolumeConfigurator
  fullName: SombraStudios.Shared.Audio.AudioVolumeConfigurator
- uid: SombraStudios.Shared.Audio.AudioVolumeConfigurator.SetMainVolume*
  commentId: Overload:SombraStudios.Shared.Audio.AudioVolumeConfigurator.SetMainVolume
  href: SombraStudios.Shared.Audio.AudioVolumeConfigurator.html#SombraStudios_Shared_Audio_AudioVolumeConfigurator_SetMainVolume_System_Single_
  name: SetMainVolume
  nameWithType: AudioVolumeConfigurator.SetMainVolume
  fullName: SombraStudios.Shared.Audio.AudioVolumeConfigurator.SetMainVolume
- uid: System.Single
  commentId: T:System.Single
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.single
  name: float
  nameWithType: float
  fullName: float
  nameWithType.vb: Single
  fullName.vb: Single
  name.vb: Single
- uid: SombraStudios.Shared.Audio.AudioVolumeConfigurator.SetMusicVolume*
  commentId: Overload:SombraStudios.Shared.Audio.AudioVolumeConfigurator.SetMusicVolume
  href: SombraStudios.Shared.Audio.AudioVolumeConfigurator.html#SombraStudios_Shared_Audio_AudioVolumeConfigurator_SetMusicVolume_System_Single_
  name: SetMusicVolume
  nameWithType: AudioVolumeConfigurator.SetMusicVolume
  fullName: SombraStudios.Shared.Audio.AudioVolumeConfigurator.SetMusicVolume
