### YamlMime:ManagedReference
items:
- uid: SombraStudios.Shared.Gameplay.Behaviours.LookWithLerp.LookWithLerpSettings
  commentId: T:SombraStudios.Shared.Gameplay.Behaviours.LookWithLerp.LookWithLerpSettings
  id: LookWithLerpSettings
  parent: SombraStudios.Shared.Gameplay.Behaviours.LookWithLerp
  children:
  - SombraStudios.Shared.Gameplay.Behaviours.LookWithLerp.LookWithLerpSettings.ForwardVector
  - SombraStudios.Shared.Gameplay.Behaviours.LookWithLerp.LookWithLerpSettings.Speed
  - SombraStudios.Shared.Gameplay.Behaviours.LookWithLerp.LookWithLerpSettings.UpVector
  langs:
  - csharp
  - vb
  name: LookWithLerpSettings
  nameWithType: LookWithLerpSettings
  fullName: SombraStudios.Shared.Gameplay.Behaviours.LookWithLerp.LookWithLerpSettings
  type: Class
  source:
    remote:
      path: Gameplay/Behaviours/LookWithLerp/LookWithLerpSettings.cs
      branch: main
      repo: https://github.com/manuelfalonso/Unity-Scripts.git
    id: LookWithLerpSettings
    path: ../Gameplay/Behaviours/LookWithLerp/LookWithLerpSettings.cs
    startLine: 7
  assemblies:
  - SombraStudios.Shared.Gameplay
  namespace: SombraStudios.Shared.Gameplay.Behaviours.LookWithLerp
  summary: ScriptableObject to store settings for the "Look With Lerp" functionality.
  example: []
  syntax:
    content: >-
      [CreateAssetMenu(fileName = "LookWithLerpSettings", menuName = "Sombra Studios/Behaviours/LookWithLerpSettings")]

      public class LookWithLerpSettings : ScriptableObject
    content.vb: >-
      <CreateAssetMenu(fileName:="LookWithLerpSettings", menuName:="Sombra Studios/Behaviours/LookWithLerpSettings")>

      Public Class LookWithLerpSettings Inherits ScriptableObject
  inheritance:
  - System.Object
  - UnityEngine.Object
  - UnityEngine.ScriptableObject
  attributes:
  - type: UnityEngine.CreateAssetMenuAttribute
    ctor: UnityEngine.CreateAssetMenuAttribute.#ctor
    arguments: []
    namedArguments:
    - name: fileName
      type: System.String
      value: LookWithLerpSettings
    - name: menuName
      type: System.String
      value: Sombra Studios/Behaviours/LookWithLerpSettings
- uid: SombraStudios.Shared.Gameplay.Behaviours.LookWithLerp.LookWithLerpSettings.ForwardVector
  commentId: F:SombraStudios.Shared.Gameplay.Behaviours.LookWithLerp.LookWithLerpSettings.ForwardVector
  id: ForwardVector
  parent: SombraStudios.Shared.Gameplay.Behaviours.LookWithLerp.LookWithLerpSettings
  langs:
  - csharp
  - vb
  name: ForwardVector
  nameWithType: LookWithLerpSettings.ForwardVector
  fullName: SombraStudios.Shared.Gameplay.Behaviours.LookWithLerp.LookWithLerpSettings.ForwardVector
  type: Field
  source:
    remote:
      path: Gameplay/Behaviours/LookWithLerp/LookWithLerpSettings.cs
      branch: main
      repo: https://github.com/manuelfalonso/Unity-Scripts.git
    id: ForwardVector
    path: ../Gameplay/Behaviours/LookWithLerp/LookWithLerpSettings.cs
    startLine: 15
  assemblies:
  - SombraStudios.Shared.Gameplay
  namespace: SombraStudios.Shared.Gameplay.Behaviours.LookWithLerp
  syntax:
    content: >-
      [Header("LookWithLerp Settings")]

      public Vector3 ForwardVector
    return:
      type: UnityEngine.Vector3
    content.vb: >-
      <Header("LookWithLerp Settings")>

      Public ForwardVector As Vector3
  attributes:
  - type: UnityEngine.HeaderAttribute
    ctor: UnityEngine.HeaderAttribute.#ctor(System.String)
    arguments:
    - type: System.String
      value: LookWithLerp Settings
- uid: SombraStudios.Shared.Gameplay.Behaviours.LookWithLerp.LookWithLerpSettings.UpVector
  commentId: F:SombraStudios.Shared.Gameplay.Behaviours.LookWithLerp.LookWithLerpSettings.UpVector
  id: UpVector
  parent: SombraStudios.Shared.Gameplay.Behaviours.LookWithLerp.LookWithLerpSettings
  langs:
  - csharp
  - vb
  name: UpVector
  nameWithType: LookWithLerpSettings.UpVector
  fullName: SombraStudios.Shared.Gameplay.Behaviours.LookWithLerp.LookWithLerpSettings.UpVector
  type: Field
  source:
    remote:
      path: Gameplay/Behaviours/LookWithLerp/LookWithLerpSettings.cs
      branch: main
      repo: https://github.com/manuelfalonso/Unity-Scripts.git
    id: UpVector
    path: ../Gameplay/Behaviours/LookWithLerp/LookWithLerpSettings.cs
    startLine: 20
  assemblies:
  - SombraStudios.Shared.Gameplay
  namespace: SombraStudios.Shared.Gameplay.Behaviours.LookWithLerp
  summary: The vector that defines in which direction up is.
  example: []
  syntax:
    content: public Vector3 UpVector
    return:
      type: UnityEngine.Vector3
    content.vb: Public UpVector As Vector3
- uid: SombraStudios.Shared.Gameplay.Behaviours.LookWithLerp.LookWithLerpSettings.Speed
  commentId: F:SombraStudios.Shared.Gameplay.Behaviours.LookWithLerp.LookWithLerpSettings.Speed
  id: Speed
  parent: SombraStudios.Shared.Gameplay.Behaviours.LookWithLerp.LookWithLerpSettings
  langs:
  - csharp
  - vb
  name: Speed
  nameWithType: LookWithLerpSettings.Speed
  fullName: SombraStudios.Shared.Gameplay.Behaviours.LookWithLerp.LookWithLerpSettings.Speed
  type: Field
  source:
    remote:
      path: Gameplay/Behaviours/LookWithLerp/LookWithLerpSettings.cs
      branch: main
      repo: https://github.com/manuelfalonso/Unity-Scripts.git
    id: Speed
    path: ../Gameplay/Behaviours/LookWithLerp/LookWithLerpSettings.cs
    startLine: 26
  assemblies:
  - SombraStudios.Shared.Gameplay
  namespace: SombraStudios.Shared.Gameplay.Behaviours.LookWithLerp
  summary: The velocity applied to the Lerp.
  example: []
  syntax:
    content: >-
      [Min(0)]

      public float Speed
    return:
      type: System.Single
    content.vb: >-
      <Min(0)>

      Public Speed As Single
  attributes:
  - type: UnityEngine.MinAttribute
    ctor: UnityEngine.MinAttribute.#ctor(System.Single)
    arguments:
    - type: System.Single
      value: 0
references:
- uid: SombraStudios.Shared.Gameplay.Behaviours.LookWithLerp
  commentId: N:SombraStudios.Shared.Gameplay.Behaviours.LookWithLerp
  href: SombraStudios.html
  name: SombraStudios.Shared.Gameplay.Behaviours.LookWithLerp
  nameWithType: SombraStudios.Shared.Gameplay.Behaviours.LookWithLerp
  fullName: SombraStudios.Shared.Gameplay.Behaviours.LookWithLerp
  spec.csharp:
  - uid: SombraStudios
    name: SombraStudios
    href: SombraStudios.html
  - name: .
  - uid: SombraStudios.Shared
    name: Shared
    href: SombraStudios.Shared.html
  - name: .
  - uid: SombraStudios.Shared.Gameplay
    name: Gameplay
    href: SombraStudios.Shared.Gameplay.html
  - name: .
  - uid: SombraStudios.Shared.Gameplay.Behaviours
    name: Behaviours
    href: SombraStudios.Shared.Gameplay.Behaviours.html
  - name: .
  - uid: SombraStudios.Shared.Gameplay.Behaviours.LookWithLerp
    name: LookWithLerp
    href: SombraStudios.Shared.Gameplay.Behaviours.LookWithLerp.html
  spec.vb:
  - uid: SombraStudios
    name: SombraStudios
    href: SombraStudios.html
  - name: .
  - uid: SombraStudios.Shared
    name: Shared
    href: SombraStudios.Shared.html
  - name: .
  - uid: SombraStudios.Shared.Gameplay
    name: Gameplay
    href: SombraStudios.Shared.Gameplay.html
  - name: .
  - uid: SombraStudios.Shared.Gameplay.Behaviours
    name: Behaviours
    href: SombraStudios.Shared.Gameplay.Behaviours.html
  - name: .
  - uid: SombraStudios.Shared.Gameplay.Behaviours.LookWithLerp
    name: LookWithLerp
    href: SombraStudios.Shared.Gameplay.Behaviours.LookWithLerp.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: UnityEngine.Object
  commentId: T:UnityEngine.Object
  parent: UnityEngine
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: UnityEngine.Object
- uid: UnityEngine.ScriptableObject
  commentId: T:UnityEngine.ScriptableObject
  parent: UnityEngine
  isExternal: true
  name: ScriptableObject
  nameWithType: ScriptableObject
  fullName: UnityEngine.ScriptableObject
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: UnityEngine
  commentId: N:UnityEngine
  isExternal: true
  name: UnityEngine
  nameWithType: UnityEngine
  fullName: UnityEngine
- uid: UnityEngine.Vector3
  commentId: T:UnityEngine.Vector3
  parent: UnityEngine
  isExternal: true
  name: Vector3
  nameWithType: Vector3
  fullName: UnityEngine.Vector3
- uid: System.Single
  commentId: T:System.Single
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.single
  name: float
  nameWithType: float
  fullName: float
  nameWithType.vb: Single
  fullName.vb: Single
  name.vb: Single
